version: '3.8'

services:
  node:
    image: AddImageHere
    ports:
      - 8444:8444
      - 8447:8447 
      - 127.0.0.1:8666:8666
    restart: always
    container_name: ChiaNode
    volumes:
      - /externalplotpath:/internalplotpath #Add more plot directories here
      # /yoursecondplotpath:/plots2
      - /logpath:/root/.chia/mainnet/log
      - /datapath/db:/root/.chia/mainnet/db
      - /datapath/wallet:/root.chia/mainnet/wallet
    cap_add:
      - NET_ADMIN
    env_file:
      - node.env