version: '3.8'

services:
  node:
    image: AddImageHere
    ports:
      - 8444:8444
      - 8447:8447 
      - 127.0.0.1:8666:8666
    restart: always
    container_name: ChiaNode
    volumes:
      - /yourplotspath:/plots #Add more plot directories here
      # /yoursecondplotpath:/plots2
      - /yourlogspath:/root/.chia/mainnet/log
      - /yourconfigpath:/root/.chia/mainnet/config
    cap_add:
      - NET_ADMIN
    env_file:
      - node.env