version: '3.8'

services:
  miner:
    image: chiapoolminer
    ports:
      - 127.0.0.1:8888:8888
    restart: always
    container_name: ChiaPoolMiner
    volumes:
      - /yourplotspath:/plots #Add more plot directories here
      # /yoursecondplotpath:/plots2
    env_file:
      - miner.env