version: '3.8'

services:
  harvester:
    image: ChiaPoolMiner
    ports:
      - 127.0.0.1:8888:8888
    restart: always
    container_name: ChiaHarvester
    volumes:
      - /yourplotspath:/plots #Add more plot directories here
      # /yoursecondplotpath:/plots2
    env_file:
      - miner.env