version: '3.8'

services:
  harvester:
    image: AddImageHere
    ports:
      - 127.0.0.1:8555:8555
    restart: always
    container_name: ChiaPlotter
    volumes:
      - /yourplotspath:/plots #Add more plot directories here
      # /yoursecondplotpath:/plots2
      - /yourlogspath:/root/.chia/mainnet/log
    env_file:
      - plotter.env